name: Build and Release Minecraft Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write # ให้สิทธิ์ในการสร้าง release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: release-${{ steps.date.outputs.date }}
        name: Release ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
